# Generated by Django 5.1.3 on 2024-11-05 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update_at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update_at')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('factory_year', models.IntegerField(null=True, verbose_name='Factory year')),
                ('model_year', models.IntegerField(null=True, verbose_name='Model year')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.brand', verbose_name='Brand')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Cars',
                'ordering': ['model'],
            },
        ),
    ]
